services:
  - type: web
    name: reimagine-ai-web
    runtime: static
    buildCommand: bash scripts/render_build_flutter_web.sh
    staticPublishPath: mobile/build/web
    envVars:
      - key: API_BASE_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
